// navi-character- の catalog.json をもとにしたモンスター一覧
// 難易度ごとに、ナビアン / エボナビ / ボスナビを使用する。
const MONSTER_GROUPS = {
  easy: [
  [
    "はっぱリス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/happa-squirrel-leafy.webp"
  ],
  [
    "ひのこイモリ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/hinoko-ember-newt.webp"
  ],
  [
    "りんごキノコ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/kinoko-apple-mushroom.webp"
  ],
  [
    "こもりんナイトバット",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/komorin-little-night-bat.webp"
  ],
  [
    "ころゴーレム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/koro-golem-pebble-golem.webp"
  ],
  [
    "もふウルフ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/mofu-wolf-frost-pup.webp"
  ],
  [
    "ぷるんスライム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/purun-little-magic-slime.webp"
  ],
  [
    "ゆきまるスノーパフ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/yukimaru-snow-puff.webp"
  ],
  [
    "どんぐりリーフ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/acorn-leafy.webp"
  ],
  [
    "エンバーフロストパップ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/ember-frost-pup.webp"
  ],
  [
    "森ぷる",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/forest-puru.webp"
  ],
  [
    "モスこいしゴーレム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/moss-pebble-golem.webp"
  ],
  [
    "さくらスノーパフ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/sakura-snow-puff.webp"
  ],
  [
    "サンドエンバーイモリ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/sand-ember-newt.webp"
  ],
  [
    "スノーキノコ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/snow-mushroom.webp"
  ],
  [
    "スターバット",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/star-bat.webp"
  ],
  [
    "オータムキノコ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/autumn-mushroom.webp"
  ],
  [
    "ベリーリーフ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/berry-leafy.webp"
  ],
  [
    "ナイトスノーパフ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/night-snow-puff.webp"
  ],
  [
    "雨ふりバット",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/rainy-bat.webp"
  ],
  [
    "スプリングモスパップ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/spring-moss-pup.webp"
  ],
  [
    "サンセットぷる",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/sunset-puru.webp"
  ],
  [
    "サンストーンゴーレム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/sunstone-golem.webp"
  ],
  [
    "タイダルイモリ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/tidal-newt.webp"
  ],
  [
    "みずたまカッパ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/mizutama-kappa.webp"
  ],
  [
    "クローバーマンドラゴラ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/clover-mandragora.webp"
  ],
  [
    "コーラルバブルクラブ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/coral-bubble-crab.webp"
  ],
  [
    "ランタンホタル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/lantern-firefly.webp"
  ],
  [
    "サンダースパークフォックス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/thunder-spark-fox.webp"
  ],
  [
    "月夜のモス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/moon-moth.webp"
  ],
  [
    "くもあめウサギ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/cloud-rain-rabbit.webp"
  ],
  [
    "ハニカムビー",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/honeycomb-bee.webp"
  ],
  [
    "ヴァインカメレオン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/vine-chameleon.webp"
  ],
  [
    "こいしラム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/pebble-ram.webp"
  ],
  [
    "エンバーランタン・サラマンダー",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/ember-lantern-salamander.webp"
  ],
  [
    "たそがれフクロウ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/dusk-feather-owl.webp"
  ],
  [
    "レインボーシェル・スネイル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/rainbow-shell-snail.webp"
  ],
  [
    "みずたまりマドリン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/puddle-mudling.webp"
  ],
  [
    "シャドウクレストフェレット",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/shadow-crest-ferret.webp"
  ],
  [
    "バブルフィンカエル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/bubblefin-frog.webp"
  ],
  [
    "ピーチパフパンダ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/peach-puff-panda.webp"
  ],
  [
    "スプラウトシェルカメ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/sprout-shell-turtle.webp"
  ],
  [
    "リボンテイルねずみ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/ribbon-tailed-mouse.webp"
  ],
  [
    "ハニードロップベア",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/honeydrop-bear.webp"
  ],
  [
    "シャドウクレストリンクス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/shadow-crest-lynx.webp"
  ],
  [
    "コバルトブレードカマキリ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/cobalt-blade-mantis.webp"
  ],
  [
    "ストームホーンキッド",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/stormhorn-kid.webp"
  ],
  [
    "エンバーウィングレイヴン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/emberwing-raven.webp"
  ],
  [
    "フロストファングイタチ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/frostfang-weasel.webp"
  ],
  [
    "アイアンリーフパンサー",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/ironleaf-panther.webp"
  ],
  [
    "プリズムテイルドレイク",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/prism-tail-drake.webp"
  ],
  [
    "サンダークローラム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/thunderclaw-ram.webp"
  ],
  [
    "ダスクブレードフォックス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/duskblade-fox.webp"
  ],
  [
    "グレイシャークレストホーク",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/glacier-crest-hawk.webp"
  ],
  [
    "スカイフィンシャーク",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/skyfin-shark.webp"
  ],
  [
    "オーロラシェルリザード",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/aurora-shell-lizard.webp"
  ],
  [
    "ささやきマスクインプ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/whispering-mask-imp.webp"
  ],
  [
    "ランタンアイモス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/lantern-eye-moth.webp"
  ],
  [
    "ホロウハットかかし",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/hollow-hat-scarecrow.webp"
  ],
  [
    "ルートタングルゴブリン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/root-tangle-goblin.webp"
  ],
  [
    "みずうみミラー精霊",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/pond-mirror-spirit.webp"
  ],
  [
    "シャドウあやつりネコ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/shadow-puppet-cat.webp"
  ],
  [
    "月あかりウィスプ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/moonlit-wisp.webp"
  ],
  [
    "キャンディコーラルナメクジ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/candy-coral-slug.webp"
  ],
  [
    "コグホイール甲虫",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/cogwheel-beetle.webp"
  ],
  [
    "ペーパーつる精霊",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/paper-crane-spirit.webp"
  ],
  [
    "モッシーヤマアラシ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/mossy-porcupine.webp"
  ],
  [
    "ヴァイオレットリーフタツノオトシゴ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/violet-reef-seahorse.webp"
  ],
  [
    "ギアビットねずみ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/gearbit-mouse.webp"
  ],
  [
    "スチームスプロケット・モグラ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/steam-sprocket-mole.webp"
  ],
  [
    "リベットブルーム甲虫",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako/rivet-bloom-beetle.webp"
  ]
],
  normal: [
  [
    "はっぱリス・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/happa-squirrel-leafy-evolved.webp"
  ],
  [
    "ひのこイモリ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/hinoko-ember-newt-evolved.webp"
  ],
  [
    "りんごキノコ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/kinoko-apple-mushroom-evolved.webp"
  ],
  [
    "こもりんナイトバット・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/komorin-little-night-bat-evolved.webp"
  ],
  [
    "ころゴーレム・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/koro-golem-pebble-golem-evolved.webp"
  ],
  [
    "もふウルフ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/mofu-wolf-frost-pup-evolved.webp"
  ],
  [
    "ぷるんスライム・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/purun-little-magic-slime-evolved.webp"
  ],
  [
    "ゆきまるスノーパフ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/yukimaru-snow-puff-evolved.webp"
  ],
  [
    "どんぐりリーフ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/acorn-leafy-evolved.webp"
  ],
  [
    "エンバーフロストパップ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/ember-frost-pup-evolved.webp"
  ],
  [
    "森ぷる・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/forest-puru-evolved.webp"
  ],
  [
    "モスこいしゴーレム・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/moss-pebble-golem-evolved.webp"
  ],
  [
    "さくらスノーパフ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/sakura-snow-puff-evolved.webp"
  ],
  [
    "サンドエンバーイモリ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/sand-ember-newt-evolved.webp"
  ],
  [
    "スノーキノコ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/snow-mushroom-evolved.webp"
  ],
  [
    "スターバット・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/star-bat-evolved.webp"
  ],
  [
    "オータムキノコ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/autumn-mushroom-evolved.webp"
  ],
  [
    "ベリーリーフ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/berry-leafy-evolved.webp"
  ],
  [
    "ナイトスノーパフ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/night-snow-puff-evolved.webp"
  ],
  [
    "雨ふりバット・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/rainy-bat-evolved.webp"
  ],
  [
    "スプリングモスパップ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/spring-moss-pup-evolved.webp"
  ],
  [
    "サンセットぷる・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/sunset-puru-evolved.webp"
  ],
  [
    "サンストーンゴーレム・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/sunstone-golem-evolved.webp"
  ],
  [
    "タイダルイモリ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/tidal-newt-evolved.webp"
  ],
  [
    "みずたまカッパ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/mizutama-kappa-evolved.webp"
  ],
  [
    "クローバーマンドラゴラ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/clover-mandragora-evolved.webp"
  ],
  [
    "コーラルバブルクラブ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/coral-bubble-crab-evolved.webp"
  ],
  [
    "ランタンホタル・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/lantern-firefly-evolved.webp"
  ],
  [
    "サンダースパークフォックス・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/thunder-spark-fox-evolved.webp"
  ],
  [
    "月夜のモス・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/moon-moth-evolved.webp"
  ],
  [
    "くもあめウサギ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/cloud-rain-rabbit-evolved.webp"
  ],
  [
    "ハニカムビー・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/honeycomb-bee-evolved.webp"
  ],
  [
    "ヴァインカメレオン・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/vine-chameleon-evolved.webp"
  ],
  [
    "こいしラム・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/pebble-ram-evolved.webp"
  ],
  [
    "エンバーランタン・サラマンダー・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/ember-lantern-salamander-evolved.webp"
  ],
  [
    "たそがれフクロウ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/dusk-feather-owl-evolved.webp"
  ],
  [
    "レインボーシェル・スネイル・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/rainbow-shell-snail-evolved.webp"
  ],
  [
    "みずたまりマドリン・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/puddle-mudling-evolved.webp"
  ],
  [
    "バブルフィンカエル・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/bubblefin-frog-evolved.webp"
  ],
  [
    "キャンディコーラルナメクジ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/candy-coral-slug-evolved.webp"
  ],
  [
    "コバルトブレードカマキリ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/cobalt-blade-mantis-evolved.webp"
  ],
  [
    "コグホイール甲虫・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/cogwheel-beetle-evolved.webp"
  ],
  [
    "ダスクブレードフォックス・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/duskblade-fox-evolved.webp"
  ],
  [
    "エンバーウィングレイヴン・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/emberwing-raven-evolved.webp"
  ],
  [
    "フロストファングイタチ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/frostfang-weasel-evolved.webp"
  ],
  [
    "グレイシャークレストホーク・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/glacier-crest-hawk-evolved.webp"
  ],
  [
    "ホロウハットかかし・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/hollow-hat-scarecrow-evolved.webp"
  ],
  [
    "ハニードロップベア・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/honeydrop-bear-evolved.webp"
  ],
  [
    "アイアンリーフパンサー・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/ironleaf-panther-evolved.webp"
  ],
  [
    "ランタンアイモス・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/lantern-eye-moth-evolved.webp"
  ],
  [
    "モッシーヤマアラシ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/mossy-porcupine-evolved.webp"
  ],
  [
    "月あかりウィスプ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/moonlit-wisp-evolved.webp"
  ],
  [
    "ペーパーつる精霊・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/paper-crane-spirit-evolved.webp"
  ],
  [
    "ピーチパフパンダ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/peach-puff-panda-evolved.webp"
  ],
  [
    "みずうみミラー精霊・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/pond-mirror-spirit-evolved.webp"
  ],
  [
    "プリズムテイルドレイク・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/prism-tail-drake-evolved.webp"
  ],
  [
    "リボンテイルねずみ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/ribbon-tailed-mouse-evolved.webp"
  ],
  [
    "ルートタングルゴブリン・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/root-tangle-goblin-evolved.webp"
  ],
  [
    "シャドウクレストフェレット・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/shadow-crest-ferret-evolved.webp"
  ],
  [
    "シャドウクレストリンクス・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/shadow-crest-lynx-evolved.webp"
  ],
  [
    "シャドウあやつりネコ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/shadow-puppet-cat-evolved.webp"
  ],
  [
    "スカイフィンシャーク・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/skyfin-shark-evolved.webp"
  ],
  [
    "スプラウトシェルカメ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/sprout-shell-turtle-evolved.webp"
  ],
  [
    "ストームホーンキッド・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/stormhorn-kid-evolved.webp"
  ],
  [
    "サンダークローラム・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/thunderclaw-ram-evolved.webp"
  ],
  [
    "ヴァイオレットリーフタツノオトシゴ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/violet-reef-seahorse-evolved.webp"
  ],
  [
    "ささやきマスクインプ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/whispering-mask-imp-evolved.webp"
  ],
  [
    "オーロラシェルリザード・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/aurora-shell-lizard-evolved.webp"
  ],
  [
    "ギアビットねずみ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/gearbit-mouse-evolved.webp"
  ],
  [
    "スチームスプロケット・モグラ・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/steam-sprocket-mole-evolved.webp"
  ],
  [
    "リベットブルーム甲虫・エボル",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/zako-evolved/rivet-bloom-beetle-evolved.webp"
  ]
],
  hard: [
  [
    "👑アクアスライム王",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/aqua-slime-king.webp"
  ],
  [
    "👑ばくれつイノシシ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/bakuretsu-boar.webp"
  ],
  [
    "👑クリスタルゴーレム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/crystal-golem.webp"
  ],
  [
    "👑森のホーンキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/forest-horn-king.webp"
  ],
  [
    "👑サンダーグリフォン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/thunder-griffon.webp"
  ],
  [
    "👑黄昏ネコ魔導士",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/twilight-cat-mage.webp"
  ],
  [
    "👑オータムホーンキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/autumn-horn-king.webp"
  ],
  [
    "👑ベリーイノシシキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/berry-boar-king.webp"
  ],
  [
    "👑あかつきネコメイジ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/dawn-cat-mage.webp"
  ],
  [
    "👑ムーンクリスタルゴーレム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/moon-crystal-golem.webp"
  ],
  [
    "👑太陽グリフォンキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/solar-griffon-king.webp"
  ],
  [
    "👑タイドスライムキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/tide-slime-king.webp"
  ],
  [
    "👑オーロラスライムキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/aurora-slime-king.webp"
  ],
  [
    "👑夢見ネコメイジ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/dream-cat-mage.webp"
  ],
  [
    "👑モス遺跡ホーンキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/moss-ruin-horn-king.webp"
  ],
  [
    "👑プリズムクリスタルゴーレム",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/prism-crystal-golem.webp"
  ],
  [
    "👑スカイ遺跡グリフォン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/sky-ruin-griffon.webp"
  ],
  [
    "👑ボルケーノイノシシキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/volcano-boar-king.webp"
  ],
  [
    "👑蒼天ドラゴン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/azure-sky-dragon.webp"
  ],
  [
    "👑フレアレオ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/flare-leo.webp"
  ],
  [
    "👑月夜のフェニックス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/lumina-moon-phoenix.webp"
  ],
  [
    "👑深紅の魔獣王",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/crimson-inferno-dragon.webp"
  ],
  [
    "👑フロストクリスタルライオン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/frost-crystal-lion.webp"
  ],
  [
    "👑エクリプスシャドウフェニックス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/eclipse-shadow-phoenix.webp"
  ],
  [
    "👑星喰いのノクステラ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/noxstella-star-eater.webp"
  ],
  [
    "👑コーラルタイドサーペント",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/coral-tide-serpent.webp"
  ],
  [
    "👑ストームクラウドフクロウキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/stormcloud-owl-king.webp"
  ],
  [
    "👑翠緑シェルタイタン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/verdant-shell-titan.webp"
  ],
  [
    "👑アンバー砂丘スカラベ",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/amber-dune-scarab.webp"
  ],
  [
    "👑オーロラアイスモス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/aurora-ice-moth.webp"
  ],
  [
    "👑ヴォイドムーンワイバーン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/void-moon-wyvern.webp"
  ],
  [
    "👑深海ミラーリヴァイアサン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/abyssal-mirror-leviathan.webp"
  ],
  [
    "👑グルームソーンフォレストタイタン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/gloomthorn-forest-titan.webp"
  ],
  [
    "👑ナイトヴェールレイヴンキング",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/nightveil-raven-king.webp"
  ],
  [
    "👑黒曜コメットワイバーン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/obsidian-comet-wyvern.webp"
  ],
  [
    "👑ファントムランタンドラゴン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/phantom-lantern-dragon.webp"
  ],
  [
    "👑アイアンクロック・コロッサス",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/ironclock-colossus.webp"
  ],
  [
    "👑マギテック・ギアドラゴン",
    "https://tt-sensei.github.io/navi-character-/assets/web/fantasy/monsters/boss/magitech-gear-dragon.webp"
  ]
]
};

export const NAVIAN_MONSTERS = MONSTER_GROUPS.easy;
export const EVO_MONSTERS = MONSTER_GROUPS.normal;
export const BOSS_MONSTERS = MONSTER_GROUPS.hard;

export function getMonsterPool(difficulty) {
  return MONSTER_GROUPS[difficulty] || MONSTER_GROUPS.normal;
}
